In [6]:
import numpy  as np 

py_list=[[1,2,3,4,5],[2,3,4,5,6]]

np_array = np.array(py_list)

print(np_array)
print(type(np_array))
print(np_array.ndim)    # 2 dimension
print(np_array.shape)    
print(np_array.size)     
print(np_array.dtype)
print(np_array.itemsize)
print(np_array.nbytes)


"""
A NumPy array stores the actual raw numbers packed right next to each other in one memory block,
all guaranteed to be the same type.
This means the computer doesn't need to check types repeatedly or jump around memory — it can hand the whole block to fast, 
compiled C code that processes it in one sweep. 
Speed = no repeated type-checking + no pointer-chasing + contiguous memory"""

[[1 2 3 4 5]
 [2 3 4 5 6]]
<class 'numpy.ndarray'>
2
(2, 5)
10
int64
8
80


"\nA NumPy array stores the actual raw numbers packed right next to each other in one memory block,\nall guaranteed to be the same type.\nThis means the computer doesn't need to check types repeatedly or jump around memory — it can hand the whole block to fast, \ncompiled C code that processes it in one sweep. \nSpeed = no repeated type-checking + no pointer-chasing + contiguous memory"

In [16]:
py_list1 = [1,2,4,5,6,6]

numpy_arr = np.array(py_list1)

print(numpy_arr)

print("shape:->",numpy_arr.shape)
print("ndim:->",numpy_arr.ndim)
print("size:->",numpy_arr.size)


[1 2 4 5 6 6]
shape:-> (6,)
ndim:-> 1
size:-> 6


In [17]:
py_list2 = [[1,2],[2,3],[3,4],[4,5]]
np_array = np.array(py_list2)
print(np_array)
print("shape:->",np_array.shape)
print("ndim:->",np_array.ndim)
print("size:->",np_array.size)



[[1 2]
 [2 3]
 [3 4]
 [4 5]]
shape:-> (4, 2)
ndim:-> 2
size:-> 8


In [10]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.itemsize)
print(arr.nbytes)

4
12


In [ ]:
py_list3 = [1,2,3,4,5,6]
np_arr =  np.array(py_list3)
print(type(py_list3))
print(type(np_arr))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
mixed= np.array([1,2,3,"4"])
print(type(mixed))

<class 'numpy.ndarray'>


In [ ]:
"""
NumPy Array Basics — Plain English Cheat Sheet

ndarray = a NumPy array. Just a grid of numbers, all the same type, stored tightly together.
.shape = tells you the layout. How many rows, how many columns, etc. Always comes back as a tuple (numbers in parentheses), like (4, 2) = 4 rows, 2 columns.
.size = tells you the total count of numbers in the array. Just one plain number, like 8. It's shape's numbers multiplied together.
.ndim = how many dimensions. 1 = flat list (vector). 2 = grid (matrix). 3+ = stack of grids. Easy trick: count how many numbers are inside the .shape tuple — that's your ndim.
.dtype = what type of number is stored (like int64 or float32). Every element in the array must be the SAME type.
.itemsize = how many bytes ONE element takes up. float32 = 4 bytes. int64 = 8 bytes.
.nbytes = total memory used = size × itemsize.

Golden rule to not mix them up:

shape → structure (tuple, in parentheses)
size → total count (single number)
ndim → number of dimensions (single small number, basically "how many numbers are inside shape")

Why NumPy is fast: Python lists store addresses pointing to scattered number-objects, so Python has to check each one's type before doing math — slow. NumPy stores the raw numbers packed together, all one type, so it can blast through them in fast compiled code without checking each one — fast.

One gotcha to remember: if you mix an int and a float in one array, NumPy quietly converts everything to float, so there's no data loss. If you mix numbers with a string, NumPy converts EVERYTHING to strings.
"""