In [ ]:
# creating array 

import numpy as np
np_zeros = np.zeros((3,4))
np_zero = np.zeros(3)
print(np_zero)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
np_one = np.ones(2)
np_ones = np.ones((2,3))
ones = np.ones((2,))

print(np_one,"Hi")
print(np_ones)
print(ones)


[1. 1.] Hi
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1.]


In [5]:
np_full = np.full((3,3),8)
print(np_full)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [17]:
np_empty = np.empty((2,5))
print(np_empty)

[[6.23042070e-307 4.67297040e-307 1.69121096e-306 1.89144350e-307
  2.67017691e-306]
 [1.42413555e-306 1.78019082e-306 1.37959740e-306 2.29178686e-312
  1.11253736e-308]]


In [ ]:
np_eye = np.eye (5)
print(np_eye)  

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
np_range = np.arange(0,10,2)
print(np_range)


[0 2 4 6 8]


In [20]:
np_linspace = np.linspace(20,1000,50)
print(np_linspace)

[  20.   40.   60.   80.  100.  120.  140.  160.  180.  200.  220.  240.
  260.  280.  300.  320.  340.  360.  380.  400.  420.  440.  460.  480.
  500.  520.  540.  560.  580.  600.  620.  640.  660.  680.  700.  720.
  740.  760.  780.  800.  820.  840.  860.  880.  900.  920.  940.  960.
  980. 1000.]


In [ ]:
np_logspace = np.logspace(4,5,10)
print(np_logspace)