In [ ]:
# creating array 

import numpy as np
np_zeros = np.zeros((3,4))
np_zero = np.zeros(3)
print(np_zero)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
np_one = np.ones(2)
np_ones = np.ones((2,3))
ones = np.ones((2,))

print(np_one,"Hi")
print(np_ones)
print(ones)


[1. 1.] Hi
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1.]


In [5]:
np_full = np.full((3,3),8)
print(np_full)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [17]:
np_empty = np.empty((2,5))
print(np_empty)

[[6.23042070e-307 4.67297040e-307 1.69121096e-306 1.89144350e-307
  2.67017691e-306]
 [1.42413555e-306 1.78019082e-306 1.37959740e-306 2.29178686e-312
  1.11253736e-308]]


In [ ]:
np_eye = np.eye (5)
print(np_eye)  

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
np_range = np.arange(0,10,2)
print(np_range)


[0 2 4 6 8]


In [20]:
np_linspace = np.linspace(20,1000,50)
print(np_linspace)

[  20.   40.   60.   80.  100.  120.  140.  160.  180.  200.  220.  240.
  260.  280.  300.  320.  340.  360.  380.  400.  420.  440.  460.  480.
  500.  520.  540.  560.  580.  600.  620.  640.  660.  680.  700.  720.
  740.  760.  780.  800.  820.  840.  860.  880.  900.  920.  940.  960.
  980. 1000.]


In [21]:
np_logspace = np.logspace(4,5,10)
print(np_logspace)

[ 10000.          12915.49665015  16681.005372    21544.34690032
  27825.59402207  35938.13663805  46415.88833613  59948.42503189
  77426.36826811 100000.        ]


In [22]:
"""
In real ML code, you almost never manually type out array values like np.array([1,2,3]). 
You need to generate arrays — zeros to initialize weights, random numbers to initialize neural network parameters, 
evenly spaced numbers for plotting or learning-rate schedules, identity matrices for linear algebra. 
This section is about the toolbox for generating arrays without typing every number by hand.

2. The Functions, Explained Plainly
Function	Plain English	Example
np.zeros(shape)	Array filled with all 0s	np.zeros((2,3)) → 2x3 grid of zeros
np.ones(shape)	Array filled with all 1s	np.ones((3,)) → [1,1,1]
np.full(shape, value)	Array filled with a chosen value	np.full((2,2), 7) → 2x2 grid of 7s
np.empty(shape)	Array with garbage/uninitialized values — fast because it skips filling memory. Only use when you'll overwrite every value yourself.	Unpredictable output
np.eye(n) / np.identity(n)	An n×n "identity matrix" — 1s on the diagonal, 0s elsewhere. Used constantly in linear algebra.	np.eye(3) → 3x3 with diagonal 1s
np.arange(start, stop, step)	Like Python's range(), but returns an array. Counts by fixed steps.	np.arange(0,10,2) → [0,2,4,6,8]
np.linspace(start, stop, num)	Gives you num evenly spaced numbers between start and stop (inclusive by default)	np.linspace(0,1,5) → [0, 0.25, 0.5, 0.75, 1]
np.logspace(start, stop, num)	Same idea as linspace but spaced evenly on a logarithmic (exponential) scale	Useful for learning rates, e.g. testing 0.001, 0.01, 0.1

Key difference — arange vs linspace: arange you specify the step size and it figures out how many numbers you get. linspace you specify how many numbers you want and it figures out the step size for you
"""

'\nIn real ML code, you almost never manually type out array values like np.array([1,2,3]). \nYou need to generate arrays — zeros to initialize weights, random numbers to initialize neural network parameters, \nevenly spaced numbers for plotting or learning-rate schedules, identity matrices for linear algebra. \nThis section is about the toolbox for generating arrays without typing every number by hand.\n\n2. The Functions, Explained Plainly\nFunction\tPlain English\tExample\nnp.zeros(shape)\tArray filled with all 0s\tnp.zeros((2,3)) → 2x3 grid of zeros\nnp.ones(shape)\tArray filled with all 1s\tnp.ones((3,)) → [1,1,1]\nnp.full(shape, value)\tArray filled with a chosen value\tnp.full((2,2), 7) → 2x2 grid of 7s\nnp.empty(shape)\tArray with garbage/uninitialized values — fast because it skips filling memory. Only use when you\'ll overwrite every value yourself.\tUnpredictable output\nnp.eye(n) / np.identity(n)\tAn n×n "identity matrix" — 1s on the diagonal, 0s elsewhere. Used constantly 

In [24]:
np_random = np.random.rand(2,3)
print(np_random)


[[0.7607345  0.75405364 0.34133156]
 [0.87034074 0.35672018 0.42382223]]


In [26]:
np_random = np.random.randn(4,3)
print(np_random)


[[ 0.12645593 -1.27378513 -1.218071  ]
 [ 1.1395689  -1.3689852   1.59150642]
 [-1.81078872  1.00095467  0.66059767]
 [-1.23243009 -2.47739798  1.45160689]]


In [27]:
np_random = np.random.randint(10,20,10)
print(np_random)

[18 13 12 10 16 12 19 19 12 15]


In [30]:
np_random = np.random.uniform(1,12,4)
print(np_random)

[ 5.47199808  6.99578018  8.83322457 10.15939317]


In [33]:
np_random = np.random.normal(20,10,5)
print(np_random)

[32.87805287 16.33442882 15.26641102 21.05078405 33.21526295]


In [35]:
np_random = np.random.seed(5)
print(np_random)

None


In [48]:
np_zero = np.zeros((3,3))
np_full = np.full((3,3),7)
np_arange = np.arange(0,20,5)
np_lin = np.linspace(0,20,5)
np_eye = np.eye(4)
np_rand = np.random.seed(0)   # check the imp od this by commenting this, in short it helps you to get same output everytime  od the next line
np_random = np.random.randint(1,100,5)
print(np_random)
print(np_lin)
print(np_arange)

[45 48 65 68 68]
[ 0.  5. 10. 15. 20.]
[ 0  5 10 15]


In [ ]:
'''NumPy Array Creation — Quick Notes

np.zeros((r,c)) → grid of all 0s
np.ones((r,c)) → grid of all 1s
np.full((r,c), val) → grid filled with your chosen value
np.eye(n) → identity matrix (1s on diagonal, 0s elsewhere) = "does nothing" matrix, like multiplying by 1
np.arange(start, stop, step) → like Python's range(). You give the jump size, stop is excluded.
np.linspace(start, stop, num) → you give how many numbers you want, NumPy figures out the spacing. Stop is included. Always returns floats.
np.random.rand() → random decimals, 0 to 1, flat/equal chance
np.random.randn() → random decimals, bell-curve shaped, centered at 0
np.random.randint(low, high, size) → random whole numbers
np.random.uniform(low, high, size) → random decimals, equal chance across your chosen range
np.random.normal(mean, std, size) → random decimals, bell curve, YOU pick center + spread
np.random.seed(n) → locks the "random" numbers so they repeat the same way every run. Same seed = same numbers always.

Key gotchas:

arange's count = jump-driven. linspace's count = you-decide-driven.
arange can give int output, linspace almost always gives float.
Identity matrix = matrix version of "×1" — multiply anything by it, get the same thing back.'''