In [1]:
import numpy as np 

# part 3 --> indexing

In [ ]:
my_list=[10,20,30,40,50,60,70,80,90]

np_array = np.array(my_list)

print(np_array)
print(np_array[0])
print(np_array[1:3])


my_list_2d = [[12,11],
              [10,9],
              [8,7]
              ]
np_array_2d = np.array(my_list_2d)
print(np_array_2d[0,0])
print(np_array_2d[1,1])
print(np_array_2d[:,1])

[10 20 30 40 50 60 70 80 90]
10
[20 30]
12
9
[11  9  7]


In [5]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ]
                  )
# arr2d[row_selector, column_selector]

print(arr2d[0, 0]  )   # 1        → row 0, col 0
print(arr2d[1, 2] )    # 6        → row 1, col 2
print(arr2d[0]  )      # [1 2 3]  → entire row 0
print(arr2d[:, 1] )    # [2 5 8]  → ALL rows, column 1 only
print(arr2d[2, :] )    # [7 8 9]  → row 2, all columns (same as arr2d[2])
print(arr2d[0:2, 1:3] )# [[2 3]   → rows 0-1, cols 1-2
                #  [5 6]]





1
6
[1 2 3]
[2 5 8]
[7 8 9]
[[2 3]
 [5 6]]


In [ ]:
arr3d=np.zeros((2,3,4))
# print(arr3d)
arr3d = np.zeros((2, 3, 4))  # think: 2 "sheets," each 3 rows x 4 cols
arr3d[0]        # the entire first sheet (shape 3,4)
arr3d[0, 1]     # row 1 of the first sheet (shape 4,)
arr3d[0, 1, 2]  # a single number

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]
0.0


In [18]:
# Boolean Indexing-->Very commonly used in real code 
arr= np.array([5,12,8,20,3,17])
print(arr>10)  # [False  True False  True False  True]  ← a mask
print(arr[arr>10]) # [12 20 17]   ← only the elements where the mask is True
print(arr[(arr>5) & (arr<18)])


print(np.where(arr>10))   #← returns the INDICES where condition is True, not the values
print(np.where(arr>10,"big","small"))


print(arr[[1,2,3]])

[False  True False  True False  True]
[12 20 17]
[12  8 17]
(array([1, 3, 5]),)
['small' 'big' 'small' 'big' 'small' 'big']
[12  8 20]
