In [1]:
# Reshaping,flattening ,Transposing 

import numpy as np



In [ ]:
a = np.arange(12) #	[0	1	2	3	4	5	6	7	8	9	10	11]
print(a)

b = a.reshape(3,4) #	repack	into	3	rows,	4	columns
print(b)


c = a.reshape(2,2,3)
print(c)

d=a.reshape(3,-1)
print(d)



m	=	np.array([[1,2],[3,4]])
m.flatten()			#	[1	2	3	4]		->	ALWAYS	a	COPY	—	safe	to	freely	modify
m.ravel()					
#	[1	2	3	4]		->	a	VIEW	when	possible	—	faster,	but	can	 affect	the	original
m.T		 #	TRANSPOSE:	flips	rows	and	columns									
#	[[1	3]
#		[2	4]]'



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[1, 3],
       [2, 4]])

In [ ]:
'''
Common	Errors

1.	Trying	to	reshape	into	a	total	size	that	doesn’t	match:	
np.arange(10).reshape(3,4)	fails	because	10	elements	can’t	fill	a
12-slot	shape.
2.	Confusing	.flatten()	(safe	copy)	with	.ravel()	(view,	may	share
memory).

'''

In [6]:
#Broudcasting


arr = np.array([[1,2,3],[4,5,6]])
print(arr+10)
print(arr)

[[11 12 13]
 [14 15 16]]
[[1 2 3]
 [4 5 6]]


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
row = np.array([10,20,30])

print(arr+row)

[[11 22 33]
 [14 25 36]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])   # shape (2,3)
col  = np.array([[100],[200]])        # shape (2,1)
arr + col
# [[101 102 103],
#  [204 205 206]]    
# col gets "copied" across all 3 columns

In [ ]:
a = np.array([1,2,3])       # shape (3,)
b = np.array([1,2])          # shape (2,)
a + b   # ValueError: operands could not be broadcast together

In [ ]:
"""

Broadcasting — Quick Notes
Broadcasting = NumPy's way of doing math between arrays of different shapes by automatically "stretching" the smaller one — without actually copying data.
The Rule: Compare shapes from the RIGHT side, one dimension at a time. Two dimensions are OK together if:
they're equal, OR
one of them is 1 (it stretches to match)
If neither is true → error.
Big trap: Matching numbers ANYWHERE in the shape does NOT mean compatible. Only the rightmost-aligned positions matter.
(6,3) and (3,) → compatible (3 lines up with 3) ✅
(6,3) and (6,) → NOT compatible (6 lines up with 3, not 6) ❌
Fix when it doesn't line up: reshape it so the number lands in the right (rightmost) position.
e.g. turn (6,) into (6,1) using .reshape(6,1) so it lines up correctly against (6,3).
Quick examples:
scalar + array → scalar stretches to fit whole array
(3,) row + (2,3) grid → row copied across every row
(2,1) column + (2,3) grid → column copied across every column
Real use in ML: adding a bias vector to every row of a batch, normalizing data (subtract mean, divide by std) — all done via broadcasting, no loops.
Always check .shape on both arrays before combining them — most broadcasting bugs are just "didn't check the shape."

"""