In [1]:
# Reshaping,flattening ,Transposing 

import numpy as np



In [ ]:
a = np.arange(12) #	[0	1	2	3	4	5	6	7	8	9	10	11]
print(a)

b = a.reshape(3,4) #	repack	into	3	rows,	4	columns
print(b)


c = a.reshape(2,2,3)
print(c)

d=a.reshape(3,-1)
print(d)



m	=	np.array([[1,2],[3,4]])
m.flatten()			#	[1	2	3	4]		->	ALWAYS	a	COPY	—	safe	to	freely	modify
m.ravel()					
#	[1	2	3	4]		->	a	VIEW	when	possible	—	faster,	but	can	 affect	the	original
m.T		 #	TRANSPOSE:	flips	rows	and	columns									
#	[[1	3]
#		[2	4]]'



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[1, 3],
       [2, 4]])

In [ ]:
'''
Common	Errors

1.	Trying	to	reshape	into	a	total	size	that	doesn’t	match:	
np.arange(10).reshape(3,4)	fails	because	10	elements	can’t	fill	a
12-slot	shape.
2.	Confusing	.flatten()	(safe	copy)	with	.ravel()	(view,	may	share
memory).

'''