In [ ]:
# Aggregation and axis

In [1]:
import numpy as np

In [ ]:
py_list = [12,23,34,45,56,67,78,89,90]

np_arr = np.array(py_list)

print("Sum :->",np_arr.sum())
print("Mean :->",np_arr.mean())
print("std :->",np_arr.std())  # standard deviation — how spread out the numbers are

print(np_arr.var())      # variance — std squared
print(np_arr.min())    # 1
print(np_arr.max())    # 5
print(np_arr.argmin())   # 0   → INDEX of the minimum value, not the value itself
print(np_arr.argmax())   # 4   → INDEX of the max value
print(np.median(np_arr)) # 3.0
print(np.cumsum(np_arr)) # [1 3 6 10 15]  → running total
print(np.cumprod(np_arr))# [1 2 6 24 120] → running product


Sum :-> 494
Mean :-> 54.888888888888886
std :-> 26.80980104549016
718.7654320987654
12
90
0
8
56.0
[ 12  35  69 114 170 237 315 404 494]
[             12             276            9384          422280
        23647680      1584394560    123582775680  10998867035520
 989898033196800]


In [ ]:
 # Axis

grid = np.array([[1,2,3],[4,5,6]])

print(grid.sum(axis=0))  # [5 7 9]     → sums each COLUMN (1+4, 2+5, 3+6)
print(grid.sum(axis=1))   # [6 15]      → sums each ROW (1+2+3, 4+5+6)

[5 7 9]
[ 6 15]


In [5]:
print(grid.shape)

print(grid.sum(axis=1,keepdims=True))

(2, 3)
[[ 6]
 [15]]


In [ ]:
'''
Aggregation = squashing many numbers into one summary number (or fewer numbers).
sum() → total
mean() → average
median() → middle value
std() → how spread out the numbers are
var() → std squared
min() / max() → smallest / largest value
argmin() / argmax() → index/position of smallest/largest value (not the value itself)
cumsum() → running total as you go (e.g. [1,2,3] → [1,3,6])
cumprod() → running product (e.g. [1,2,3] → [1,2,6])
axis controls which direction you're collapsing:
axis=0 → collapses rows (squash values going down each column) → one result per column
axis=1 → collapses columns (squash values going across each row) → one result per row
Trick: axis=N = "this dimension disappears from the result"
keepdims=True → keeps the collapsed dimension as a placeholder 1 instead of deleting it, so the result can still broadcast correctly against the original array. Use it when you'll do more math with the result; skip it if you just want to print/view it.
Real ML use: np.argmax(predictions, axis=1) → picks the predicted class for each sample in a batch. Extremely common line of real code.
'''