In [ ]:
import numpy as np

In [ ]:
# Reshaping 

arr = np.arange(12) # [0 1 2 3 4 5 6 7 8 9 10 11], shape (12,)


print(arr)

arr.reshape(3, 4)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

arr.reshape(4, 3)
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]


arr.reshape(3, -1)   # same as reshape(3, 4) — NumPy figures out the -1 automatically
arr.reshape(-1, 4)   # same as reshape(3, 4)
arr.reshape(-1, 1)   # shape (12, 1) — turn a flat array into a single COLUMN
arr.reshape(1, -1)   # shape (1, 12) — turn a flat array into a single ROW


In [ ]:
arr2d = np.array([[1,2],[3,4]])
flat = arr2d.flatten()   # ALWAYS returns a COPY — modifying flat won't affect arr2d
rav  = arr2d.ravel()     # returns a VIEW when possible — modifying rav MIGHT affect arr2d

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])   # shape (2,3)
arr.T
# [[1 4]
#  [2 5]
#  [3 6]]
# shape (3,2)

In [ ]:
arr3d = np.zeros((2,3,4))   # shape (2,3,4)
arr3d.swapaxes(0,1).shape   # (3,2,4)  → swaps axis 0 and axis 1, others untouched
np.moveaxis(arr3d, 0, -1).shape  # (3,4,2) → moves axis 0 to the last position

In [ ]:
arr = np.array([1,2,3])          # shape (3,)
np.expand_dims(arr, axis=0)      # shape (1,3)  → adds a dimension
np.expand_dims(arr, axis=1)      # shape (3,1)  → adds a dimension elsewhere

arr2 = np.array([[[5,6,7]]])     # shape (1,1,3)
arr2.squeeze()                    # shape (3,)   → removes ALL size-1 dimensions

In [ ]:
'''Reshaping — Quick Notes

Reshaping = rearranging the SAME numbers into a different shape. Total count (.size) must stay the same — you can't reshape 12 elements into a shape that doesn't multiply to 12.
arr.reshape(3,4) → arranges numbers into 3 rows, 4 columns. Fills row by row (left to right, top to bottom).
-1 trick: let NumPy calculate one dimension for you.
reshape(-1, 1) → turn into a single column
reshape(1, -1) → turn into a single row
reshape(3, -1) → "I want 3 rows, you figure out the columns"
flatten() → turns any array into 1D, always makes a safe copy (original untouched if you edit the flat one)
ravel() → turns any array into 1D, but usually shares memory with original — faster, but riskier
.T / transpose() → flips rows and columns (rows become columns, columns become rows)
swapaxes() / moveaxis() → for 3D+ arrays, swap or move specific axes (used e.g. rearranging image data formats)
expand_dims(arr, axis) → adds a new size-1 dimension (e.g. turn a single sample into "a batch of 1")
squeeze() → removes all size-1 dimensions (reverse of expand_dims)

Real use: flattening an image (28×28 → 784 numbers) before feeding it to a simple neural net. reshape(-1,1) to fix "column vs row" shape errors in scikit-learn.

Golden rule: always check that your target shape's numbers multiply to the same total as the original — that's 90% of reshape errors solved before they happen.

Ready to move to Part 8 (Combining Arrays)?

'''

