In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([a, b])   # [1 2 3 4 5 6]  → joins along existing axis (default axis=0)

In [ ]:
a = np.array([[1,2],[3,4]])   # shape (2,2)
b = np.array([[5,6],[7,8]])   # shape (2,2)

np.concatenate([a,b], axis=0)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]     shape (4,2)  → stacked vertically (more rows)

np.concatenate([a,b], axis=1)
# [[1 2 5 6]
#  [3 4 7 8]]     shape (2,4)  → stacked horizontally (more columns)

In [ ]:

np.vstack([a,b])   # same as concatenate axis=0 → stacks vertically (adds rows)
np.hstack([a,b])   # same as concatenate axis=1 → stacks horizontally (adds columns)

In [ ]:
a = np.array([1,2,3])   # shape (3,)
b = np.array([4,5,6])   # shape (3,)

np.stack([a,b])
# [[1 2 3]
#  [4 5 6]]
# shape (2,3)  ← a NEW axis was created, turning two 1D arrays into one 2D array

In [ ]:
arr = np.arange(9)   # [0 1 2 3 4 5 6 7 8]

np.split(arr, 3)      # [[0,1,2],[3,4,5],[6,7,8]]  → 3 EQUAL parts, error if it can't split evenly
np.array_split(arr, 4) # splits into 4 parts, allows UNEQUAL sizes if it doesn't divide evenly

In [ ]:
grid = np.arange(16).reshape(4,4)
np.vsplit(grid, 2)   # splits into 2 pieces, cutting horizontally (row-wise)
np.hsplit(grid, 2)   # splits into 2 pieces, cutting vertically (column-wise)

In [ ]:
'''
Combining & Splitting Arrays — Quick Notes

concatenate([a,b], axis=...) → joins arrays along an EXISTING axis. Result stays "flat" — no new dimension added.
python
  np.concatenate([[1,2,3],[4,5,6]])   # [1 2 3 4 5 6] — merged into one longer array
vstack → stack vertically (adds more rows) — same as concatenate axis=0
hstack → stack horizontally (adds more columns) — same as concatenate axis=1
Memory trick: "v" = vertical = downward = more rows. "h" = horizontal = sideways = more columns.
stack([a,b]) → creates a BRAND NEW dimension, keeps arrays as separate layers/rows instead of merging them flat.
python
  a = [1,2,3]; b = [4,5,6]
  np.stack([a,b])
  # [[1 2 3]
  #  [4 5 6]]   ← shape (2,3), NEW axis created

Compare: concatenate on the same two would give [1 2 3 4 5 6] — one flat array, no new dimension.

Golden rule: concatenate = join along existing axis (stays same number of dimensions). stack = create new axis (adds one more dimension).
np.split(arr, n) → splits into n EQUAL parts, errors if uneven
np.array_split(arr, n) → splits into n parts, allows uneven sizes
vsplit / hsplit → same idea but cutting a 2D grid row-wise or column-wise

Real ML example: 5 separate images, each (64,64) → want one array (5,64,64) → use stack, not concatenate, because you want a NEW "batch" dimension, not to merge the images into one giant flat grid.
'''