In [2]:
import numpy as np


In [ ]:
v = np.array([3,4])

M = np.array([[1,2],[3,4]])

np.dot(v ,M)   # 32
v @ M         # 32   → the @ operator is shorthand for dot product / matrix multiply


In [ ]:
A = np.array([[1,2,3],[4,5,6]])   # shape (2,3)
A.T                                 # shape (3,2)

In [ ]:
A = np.array([[1,2],[3,4]])
print(np.linalg.det(A))   # -2.0

In [3]:
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
print(np.linalg.inv(A))
A @ A_inv
# [[1. 0.]
#  [0. 1.]]   ← identity matrix! confirms A_inv correctly "undoes" A

[[ 0.6 -0.7]
 [-0.2  0.4]]


array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

In [ ]:
'''
Linear Algebra — Quick Notes

Vector = a list of numbers, thought of as a point/arrow in space. [3,4] = arrow to point (3,4).
Matrix = a grid of numbers (2D array). Can be seen as a "machine" that transforms vectors.
Dot product (a @ b or np.dot(a,b)): multiply matching positions, add them all up.
[1,2,3]·[4,5,6] = 1*4+2*5+3*6 = 32
Meaning: measures how much two vectors "agree" in direction. Big positive = similar direction, 0 = unrelated, negative = opposite.
THIS is the core math behind Transformer attention — "how relevant is word A to word B" = dot product of their vectors.
Matrix multiplication (A @ B): each output cell = dot product of a row from A and a column from B. Inner dimensions must match: (m,n) @ (n,p) → (m,p).
Transpose (.T): flips rows↔columns. Used to make shapes line up for matmul.
Determinant (np.linalg.det()): one number describing how a matrix scales space.
det = 0 → matrix squashes things flat → NOT invertible
det ≠ 0 → invertible
Inverse (np.linalg.inv()): "undoes" a matrix, like 5 × 1/5 = 1. A @ A_inv = identity matrix. Only exists if det ≠ 0.
np.linalg.solve(A, b) → the proper, stable way to solve Ax = b (better than computing inverse manually).
Norm (np.linalg.norm()): the "length" of a vector. norm([3,4]) = sqrt(3²+4²) = 5. Used to measure vector size / distance between embeddings.
Rank: how many truly independent (non-redundant) directions of info a matrix has.
Eigenvalues/eigenvectors (np.linalg.eig()): eigenvectors are special directions that only get STRETCHED (not rotated) by the matrix; eigenvalue = how much they stretch. Core of PCA (dimensionality reduction).
SVD (np.linalg.svd()): more general/stable relative of eigen-decomposition, works on any matrix. Used in recommender systems, dimensionality reduction

'''

In [ ]:
np.random.binomial(n=10, p=0.5, size=5)
# e.g. [4 6 5 3 7] → each number = "how many heads out of 10 flips," repeated 5 times

In [ ]:
arr = np.array([10,20,30,40,50])

np.random.choice(arr, size=3)              # pick 3 random elements, WITH repeats allowed by default
np.random.choice(arr, size=3, replace=False) # pick 3 UNIQUE elements, no repeats

np.random.permutation(arr)   # returns a shuffled COPY of the array
np.random.shuffle(arr)       # shuffles the array IN PLACE (modifies arr directly, returns None)

In [ ]:
data = np.array([50, 52, 49, 51, 200])   # one big outlier
np.mean(data)   # 80.4   → dragged upward hard by the outlier
np.std(data)    # ~59.4  → huge, because 200 is very far from the rest

In [ ]:
normalized = (data - data.mean()) / data.std()

In [ ]:
# Loop-based (slow)
result = []
for x in data:
    result.append(x * 2 + 1)

# Vectorized (fast)
result = data * 2 + 1

In [ ]:
'''Random / Statistics — Quick Notes

Distribution = the pattern a big pile of random numbers forms.
Uniform → every value equally likely (flat). np.random.uniform(0,10,5)
Normal (bell curve) → clustered near the mean, rare far away. np.random.normal(0,1,5)
Binomial → counts of "successes" out of fixed trials (like coin flips). np.random.binomial(n=10, p=0.5, size=5) → e.g. [4 6 5] = heads out of 10 flips, repeated
Sampling:
np.random.choice(arr, size=3) → pick random elements (repeats allowed by default)
np.random.choice(arr, size=3, replace=False) → no repeats
np.random.permutation(arr) → shuffled COPY (original untouched)
np.random.shuffle(arr) → shuffles IN PLACE (changes original, saves memory)
np.random.seed(42) → locks randomness so results repeat exactly — critical for reproducible experiments.
Mean/std/var (deeper meaning):
Mean = center/average
Std = how far values typically stray from mean (small = tight cluster, big = spread out)
Var = std squared
Real use — normalization:
python
  normalized = (data - data.mean()) / data.std()

Rescales data to mean 0, std 1 — near-universal ML preprocessing step.

Part 13 — Performance / Vectorization — Quick Notes

Vectorization = do math on the WHOLE array at once instead of looping element-by-element. NumPy runs it in fast compiled C code instead of slow Python.
python
# Slow (loop)
result = [x*2+1 for x in data]

# Fast (vectorized)
result = data*2 + 1
Why loops are slow: every step, Python checks the type, calls the operation, makes a new object — repeated overhead every single element.
Why vectorized is fast: one small setup cost, then runs in tight compiled code, no per-element Python overhead.
np.vectorize() is a trap — looks like it should speed things up, but it still loops internally in Python. Barely faster than a normal loop. Real speed = using NumPy's built-in ops directly (+, *, np.sqrt, boolean masks, etc.), not wrapping your own function.
Golden rule: if you're writing a for loop to do math on a NumPy array — stop, there's almost always a vectorized way instead.

Example benchmark result you should expect: vectorized code is typically 20–100x faster than the equivalent Python loop on large arrays.
'''